export const formJson = {
 status: "success",
 data: {
  0: {
   serviceID: 46,
   serviceFormID: 49,
   formData: {
    title: "Towing",
    formPages: [
     {
      pageID: 1,
      sections: [
       {
        type: "none",
        fields: [
         {
          name: "Make, Model, Year",
          value: "",
          fieldID: 1,
          dataType: "string",
          required: true,
          maxLength: 100,
          fieldOrder: 0,
          placeholder: "Ex: Honda, Civic, 2021",
         },
        ],
        sectionID: 1,
        headerText: "Vehicle Details",
        sectionOder: 0,
       },
       {
        type: "none",
        fields: [
         {
          name: "Origin Location",
          value: "",
          fieldID: 5,
          dataType: "string",
          required: true,
          maxLength: 100,
          fieldOrder: 0,
          placeholder: "Address/Street intersection",
         },
         {
          name: "Origin City",
          value: "",
          fieldID: 6,
          dataType: "string",
          required: true,
          maxLength: 100,
          fieldOrder: 1,
          placeholder: "Chicago",
         },
         {
          name: "Destination Location",
          value: "",
          fieldID: 7,
          dataType: "string",
          required: true,
          maxLength: 100,
          fieldOrder: 2,
          placeholder: "Address/Street intersection",
         },
         {
          name: "Destination City",
          value: "",
          fieldID: 8,
          dataType: "string",
          required: true,
          maxLength: 100,
          fieldOrder: 3,
          placeholder: "Lombard",
         },
        ],
        sectionID: 2,
        headerText: "Towing Details",
        sectionOder: 1,
       },
       {
        type: "radio",
        fields: [
         {
          name: "2 Wheel Drive",
          value: "",
          fieldID: 9,
          dataType: "checkbox",
          required: true,
          maxLength: 0,
          fieldOrder: 0,
          placeholder: "",
         },
         {
          name: "4 Wheel Drive",
          value: "",
          fieldID: 10,
          dataType: "checkbox",
          required: true,
          maxLength: 0,
          fieldOrder: 1,
          placeholder: "",
         },
         {
          name: "Don't Know",
          value: "",
          fieldID: 11,
          dataType: "checkbox",
          required: true,
          maxLength: 0,
          fieldOrder: 2,
          placeholder: "",
         },
        ],
        sectionID: 13,
        headerText: "Drivetrain",
        sectionOder: 10,
       },
       {
        type: "multi",
        fields: [
         {
          name: "Immediately",
          value: "",
          fieldID: 33,
          dataType: "checkbox",
          required: true,
          maxLength: 100,
          fieldOrder: 0,
         },
         {
          name: "1-5 days",
          value: "",
          fieldID: 34,
          dataType: "checkbox",
          required: true,
          maxLength: 100,
          fieldOrder: 1,
         },
         {
          name: "6-14 days",
          value: "",
          fieldID: 35,
          dataType: "checkbox",
          required: true,
          maxLength: 100,
          fieldOrder: 2,
         },
         {
          name: "15-30 days",
          value: "",
          fieldID: 36,
          dataType: "checkbox",
          required: true,
          maxLength: 100,
          fieldOrder: 3,
         },
        ],
        sectionID: 11,
        headerText: "When Did You Want the Tow?",
        sectionOder: 11,
       },
      ],
      pageOrder: 0,
     },
    ],
   },
  },
  configuration: {
   showDelgraceFeatureSectionOnTopForMobile: false,
  },
 },
 message: "Retrieved service form.",
};
