export const formJson = [
 {
  status: "success",
  data: {
   0: {
    serviceID: 46,
    serviceFormID: 49,
    formData: {
     title: "Towing",
     formPages: [
      {
       pageID: 1,
       sections: [
        {
         type: "none",
         fields: [
          {
           name: "Make, Model, Year",
           value: "",
           fieldID: 1,
           dataType: "string",
           required: true,
           maxLength: 100,
           fieldOrder: 0,
           placeholder: "Ex: Honda, Civic, 2021",
          },
         ],
         sectionID: 1,
         headerText: "Vehicle Details",
         sectionOder: 0,
        },
        {
         type: "none",
         fields: [
          {
           name: "Origin Location",
           value: "",
           fieldID: 5,
           dataType: "string",
           required: true,
           maxLength: 100,
           fieldOrder: 0,
           placeholder: "Address/Street intersection",
          },
          {
           name: "Origin City",
           value: "",
           fieldID: 6,
           dataType: "string",
           required: true,
           maxLength: 100,
           fieldOrder: 1,
           placeholder: "Chicago",
          },
          {
           name: "Destination Location",
           value: "",
           fieldID: 7,
           dataType: "string",
           required: true,
           maxLength: 100,
           fieldOrder: 2,
           placeholder: "Address/Street intersection",
          },
          {
           name: "Destination City",
           value: "",
           fieldID: 8,
           dataType: "string",
           required: true,
           maxLength: 100,
           fieldOrder: 3,
           placeholder: "Lombard",
          },
         ],
         sectionID: 2,
         headerText: "Towing Details",
         sectionOder: 1,
        },
        {
         type: "radio",
         fields: [
          {
           name: "2 Wheel Drive",
           value: "",
           fieldID: 9,
           dataType: "checkbox",
           required: true,
           maxLength: 0,
           fieldOrder: 0,
           placeholder: "",
          },
          {
           name: "4 Wheel Drive",
           value: "",
           fieldID: 10,
           dataType: "checkbox",
           required: true,
           maxLength: 0,
           fieldOrder: 1,
           placeholder: "",
          },
          {
           name: "Don't Know",
           value: "",
           fieldID: 11,
           dataType: "checkbox",
           required: true,
           maxLength: 0,
           fieldOrder: 2,
           placeholder: "",
          },
         ],
         sectionID: 13,
         headerText: "Drivetrain",
         sectionOder: 10,
        },
        {
         type: "multi",
         fields: [
          {
           name: "Immediately",
           value: "",
           fieldID: 33,
           dataType: "checkbox",
           required: true,
           maxLength: 100,
           fieldOrder: 0,
          },
          {
           name: "1-5 days",
           value: "",
           fieldID: 34,
           dataType: "checkbox",
           required: true,
           maxLength: 100,
           fieldOrder: 1,
          },
          {
           name: "6-14 days",
           value: "",
           fieldID: 35,
           dataType: "checkbox",
           required: true,
           maxLength: 100,
           fieldOrder: 2,
          },
          {
           name: "15-30 days",
           value: "",
           fieldID: 36,
           dataType: "checkbox",
           required: true,
           maxLength: 100,
           fieldOrder: 3,
          },
         ],
         sectionID: 11,
         headerText: "When Did You Want the Tow?",
         sectionOder: 11,
        },
       ],
       pageOrder: 0,
      },
     ],
    },
   },
   configuration: {
    showDelgraceFeatureSectionOnTopForMobile: false,
   },
  },
  message: "Retrieved service form.",
 },
 {
  status: "success",
  data: {
   0: {
    serviceID: 20,
    serviceFormID: 21,
    formData: {
     title: "Alternator Replacement ",
     formPages: [
      {
       pageID: 1,
       sections: [
        {
         type: "none",
         fields: [
          {
           name: "Make",
           value: "",
           fieldID: 1,
           dataType: "string",
           required: true,
           maxLength: 100,
           fieldOrder: 0,
           placeholder: "Ex: Honda",
          },
          {
           name: "Model",
           value: "",
           fieldID: 2,
           dataType: "string",
           required: true,
           maxLength: 100,
           fieldOrder: 1,
           placeholder: "Ex: Civic",
          },
          {
           name: "Trim Level or Sub Model",
           value: "",
           fieldID: 3,
           dataType: "string",
           required: false,
           maxLength: 100,
           fieldOrder: 2,
           placeholder: "Ex: LX, EX, EX-L",
          },
          {
           name: "Year",
           value: "",
           fieldID: 4,
           dataType: "string",
           required: true,
           maxLength: 100,
           fieldOrder: 3,
           placeholder: "Ex: 2019",
          },
         ],
         sectionID: 1,
         headerText: "Please provide all details about your vehicle",
         sectionOder: 0,
        },
        {
         type: "radio",
         fields: [
          {
           name: "Yes",
           value: "",
           fieldID: 6,
           dataType: "checkbox",
           required: false,
           maxLength: 100,
           fieldOrder: 0,
          },
          {
           name: "No",
           value: "",
           fieldID: 7,
           dataType: "checkbox",
           required: false,
           maxLength: 100,
           fieldOrder: 1,
          },
          {
           name: "Not sure",
           value: "",
           fieldID: 8,
           dataType: "checkbox",
           required: false,
           maxLength: 100,
           fieldOrder: 2,
          },
         ],
         sectionID: 2,
         headerText: "Do you require OEM (original equipment) parts?",
         sectionOder: 1,
        },
        {
         type: "multi",
         fields: [
          {
           name: "Immediately",
           value: "",
           fieldID: 33,
           dataType: "checkbox",
           required: true,
           maxLength: 100,
           fieldOrder: 0,
          },
          {
           name: "1-5 days",
           value: "",
           fieldID: 34,
           dataType: "checkbox",
           required: true,
           maxLength: 100,
           fieldOrder: 1,
          },
          {
           name: "6-14 days",
           value: "",
           fieldID: 35,
           dataType: "checkbox",
           required: true,
           maxLength: 100,
           fieldOrder: 2,
          },
          {
           name: "15-30 days",
           value: "",
           fieldID: 36,
           dataType: "checkbox",
           required: true,
           maxLength: 100,
           fieldOrder: 3,
          },
         ],
         sectionID: 11,
         headerText: "When would you like the service to be completed (select all that apply):",
         sectionOder: 10,
        },
        {
         type: "notes",
         fields: [
          {
           name: "notes",
           value: "",
           fieldID: 37,
           dataType: "notes",
           required: false,
           maxLength: 256,
           fieldOrder: 4,
          },
         ],
         sectionID: 12,
         headerText: "Please enter any other information that you would like the Pro to know.",
         sectionOder: 11,
        },
       ],
       pageOrder: 0,
      },
     ],
    },
   },
   configuration: {
    showDelgraceFeatureSectionOnTopForMobile: false,
   },
  },
  message: "Retrieved service form.",
 },
 {
  status: "success",
  data: {
   0: {
    serviceID: 33,
    serviceFormID: 36,
    formData: {
     title: "Ceiling Fan Installation",
     formPages: [
      {
       pageID: 1,
       sections: [
        {
         type: "none",
         fields: [
          { name: "City", value: "", fieldID: 1, dataType: "string", required: true, maxLength: 100, fieldOrder: 0, placeholder: "Ex: Chicago" },
          { name: "State", value: "", fieldID: 2, dataType: "string", required: true, maxLength: 100, fieldOrder: 1, placeholder: "Ex: IL" },
          { name: "Description of item and area for installation", value: "", fieldID: 3, dataType: "string", required: true, maxLength: 255, fieldOrder: 2, placeholder: "" },
          { name: "Link to item", value: "", fieldID: 4, dataType: "string", required: false, maxLength: 100, fieldOrder: 3, placeholder: "" },
         ],
         sectionID: 1,
         headerText: "Please provide all details about your home",
         sectionOder: 0,
        },
        {
         type: "radio",
         fields: [
          { name: "1", value: "", fieldID: 5, dataType: "checkbox", required: false, maxLength: 5, fieldOrder: 0 },
          { name: "2", value: "", fieldID: 6, dataType: "checkbox", required: false, maxLength: 5, fieldOrder: 1 },
          { name: "other", value: "", fieldID: 7, dataType: "checkbox", required: false, maxLength: 5, fieldOrder: 2 },
         ],
         sectionID: 2,
         headerText: "No of stories",
         sectionOder: 1,
        },
        {
         type: "none",
         fields: [
          { name: "Age of building", value: "", fieldID: 8, dataType: "string", required: false, maxLength: 50, fieldOrder: 0 },
          { name: "Ceiling Height", value: "", fieldID: 9, dataType: "string", required: false, maxLength: 50, fieldOrder: 1 },
         ],
         sectionID: 3,
         headerText: "Home information",
         sectionOder: 2,
        },
        {
         type: "radio",
         fields: [
          { name: "Swap", value: "", fieldID: 10, dataType: "checkbox", required: false, maxLength: 5, fieldOrder: 0 },
          { name: "New", value: "", fieldID: 11, dataType: "checkbox", required: false, maxLength: 5, fieldOrder: 1 },
         ],
         sectionID: 4,
         headerText: "Installation Type",
         sectionOder: 3,
        },
        {
         type: "radio",
         fields: [
          { name: "Yes", value: "", fieldID: 1, dataType: "radio", required: true, maxLength: 0, fieldOrder: 0, placeholder: "" },
          { name: "No", value: "", fieldID: 2, dataType: "radio", required: true, maxLength: 0, fieldOrder: 1, placeholder: "" },
         ],
         sectionID: 13,
         headerText: "Is the new ceiling fan remote controlled?",
         sectionOder: 4,
        },
        {
         type: "radio",
         fields: [
          { name: "Yes", value: "", fieldID: 3, dataType: "radio", required: true, maxLength: 0, fieldOrder: 0, placeholder: "" },
          { name: "No", value: "", fieldID: 4, dataType: "radio", required: true, maxLength: 0, fieldOrder: 1, placeholder: "" },
         ],
         sectionID: 13,
         headerText: "Is the old ceiling fan working?",
         sectionOder: 9,
        },
        {
         type: "multi",
         fields: [
          { name: "Weekdays 8am-5pm", value: "", fieldID: 28, dataType: "checkbox", required: true, maxLength: 100, fieldOrder: 0 },
          { name: "Weeknights 6pm-9pm", value: "", fieldID: 29, dataType: "checkbox", required: true, maxLength: 100, fieldOrder: 1 },
          { name: "Weekends 8am-1pm", value: "", fieldID: 30, dataType: "checkbox", required: true, maxLength: 100, fieldOrder: 2 },
          { name: "Weekends 2pm-9pm", value: "", fieldID: 31, dataType: "checkbox", required: true, maxLength: 100, fieldOrder: 3 },
          { name: "Anytime", value: "", fieldID: 32, dataType: "checkbox", required: true, maxLength: 100, fieldOrder: 4 },
         ],
         sectionID: 10,
         headerText: "Please select timings that work for you (select all that apply):",
         sectionOder: 11,
        },
        {
         type: "multi",
         fields: [
          { name: "Immediately", value: "", fieldID: 33, dataType: "checkbox", required: true, maxLength: 100, fieldOrder: 0 },
          { name: "1-5 days", value: "", fieldID: 34, dataType: "checkbox", required: true, maxLength: 100, fieldOrder: 1 },
          { name: "6-14 days", value: "", fieldID: 35, dataType: "checkbox", required: true, maxLength: 100, fieldOrder: 2 },
          { name: "15-30 days", value: "", fieldID: 36, dataType: "checkbox", required: true, maxLength: 100, fieldOrder: 3 },
         ],
         sectionID: 11,
         headerText: "When would you like the service to be completed (select all that apply):",
         sectionOder: 12,
        },
        { type: "notes", fields: [{ name: "notes", value: "", fieldID: 37, dataType: "notes", required: false, maxLength: 256, fieldOrder: 4 }], sectionID: 12, headerText: "Please enter any other information that you would like the Pro to know.", sectionOder: 13 },
       ],
       pageOrder: 0,
      },
     ],
    },
   },
   configuration: { showDelgraceFeatureSectionOnTopForMobile: false },
  },
  message: "Retrieved service form.",
 },
 {
  status: "success",
  data: {
   0: {
    serviceID: 73,
    serviceFormID: 77,
    formData: {
     title: "Surface Disinfecting",
     formPages: [
      {
       pageID: 1,
       sections: [
        {
         type: "none",
         fields: [
          { name: "City", value: "", fieldID: 1, dataType: "string", required: true, maxLength: 100, fieldOrder: 0, placeholder: "Ex: Chicago" },
          { name: "State", value: "", fieldID: 2, dataType: "string", required: true, maxLength: 100, fieldOrder: 1, placeholder: "Ex: IL" },
         ],
         sectionID: 1,
         headerText: "Location Details",
         sectionOder: 0,
        },
        { type: "notes", fields: [{ name: "Service Description", value: "", fieldID: 3, dataType: "notes", required: true, maxLength: 256, fieldOrder: 0 }], sectionID: 2, headerText: "Request Details", sectionOder: 1 },
        {
         type: "multi",
         fields: [
          { name: "Immediately", value: "", fieldID: 4, dataType: "checkbox", required: false, maxLength: 100, fieldOrder: 0 },
          { name: "1-5 days", value: "", fieldID: 5, dataType: "checkbox", required: false, maxLength: 100, fieldOrder: 1 },
          { name: "6-14 days", value: "", fieldID: 6, dataType: "checkbox", required: false, maxLength: 100, fieldOrder: 2 },
          { name: "15-30 days", value: "", fieldID: 7, dataType: "checkbox", required: false, maxLength: 100, fieldOrder: 3 },
         ],
         sectionID: 3,
         headerText: "Time Frame for Completion (select all that apply)",
         sectionOder: 2,
        },
        { type: "notes", fields: [{ name: "notes", value: "", fieldID: 13, dataType: "notes", required: false, maxLength: 256, fieldOrder: 0 }], sectionID: 4, headerText: "Other Details", sectionOder: 3 },
       ],
       pageOrder: 0,
      },
     ],
    },
   },
   configuration: { showDelgraceFeatureSectionOnTopForMobile: false },
  },
  message: "Retrieved service form.",
 },
];
